POST http://localhost:8080/auth/token
Content-Type: application/json

{
  "username": "Kenda",
  "password": "Kenda"
}

###

POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "password": "Kenda",
  "username": "Kenda",
  "email": "Kenda@gmail.com",
  "profile": "Kenda Profile",
  "roles": [
    "ADMIN"
  ]
}

###
